### ISSUE TITLE
Optgroup arguments didn't work with named array.

### ISSUE THREAD

**Issue by macchaka** [EFTEC/BladeOneHtml#1]
at line 692
```
echo \"<optgroup label='{$args['optgroup']}'>\";
```
When  I was set argument like `optgroup=$pref['group']`,
BladeOneHtml builds html the below.

```
echo "<optgroup label='$pref['group']'>";
```

I found optgroup arguments are wraped `$this->e`method in option tag.
I can't find how to wrap by `$this->e` without using wrapPHP method.
I modified like the below.

```
echo \"<optgroup label='\"." . '$this->e' . "({$args['optgroup']}).\"'>\";
```

It works well.

```
echo "<optgroup label='".$this->e($pref['group'])."'>";
```

**Comment by jorgecc** [comment]
fixed.
